#!/usr/bin/env python3
"""
Build-time string encryption tool — matches 太阳神 DecryptSpace pattern.
Uses splitmix64 PRNG to encrypt sensitive strings, generates C header with
encrypted data + runtime DecryptSpace() function.

Usage:
    python3 tools/encrypt_strings.py strings.txt src/EncryptedStrings.h

Input format (strings.txt):
    "SBSAccessibilityWindowHostingController"
    "registerWindowWithContextID:atLevel:"
    ...

Output: C header with encrypted byte arrays and DecryptSpace() dispatch function.
"""

import sys
import struct

# splitmix64 constants (matches the reference implementation)
MULT1 = 0xBF58476D1CE4E5B9
MULT2 = 0x94D049BB133111EB
PHI   = 0x61C8864680B583EB  # golden ratio step


def splitmix64_next(state):
    """Advance splitmix64 state and return next random value."""
    z = state[0]
    z = (MULT1 * (z ^ (z >> 30))) & 0xFFFFFFFFFFFFFFFF
    z = (MULT2 * (z ^ (z >> 27))) & 0xFFFFFFFFFFFFFFFF
    state[0] = (state[0] - PHI) & 0xFFFFFFFFFFFFFFFF
    return z ^ (z >> 31)


def encrypt_string(plaintext, seed):
    """Encrypt a UTF-8 string with splitmix64 XOR stream."""
    data = plaintext.encode('utf-8')
    state = [seed & 0xFFFFFFFFFFFFFFFF]
    encrypted = bytearray()
    for byte in data:
        r = splitmix64_next(state)
        key_byte = (r >> 31) ^ r
        encrypted.append(byte ^ (key_byte & 0xFF))
    return bytes(encrypted)


def encrypt_with_neon_xor(plaintext, key_bytes):
    """Encrypt a string with simple XOR for NEON (single-key mode)."""
    data = plaintext.encode('utf-8')
    key = key_bytes.encode('utf-8') if isinstance(key_bytes, str) else key_bytes
    encrypted = bytearray()
    for i, byte in enumerate(data):
        encrypted.append(byte ^ key[i % len(key)])
    return bytes(encrypted)


def bytes_to_c_array(data, name):
    """Format bytes as a C array."""
    hex_str = ', '.join(f'0x{b:02X}' for b in data)
    return f'static const uint8_t {name}[{len(data)}] = {{{hex_str}}};'


def generate_header(strings_file, output_file):
    """Generate C header with encrypted strings and DecryptSpace function."""
    with open(strings_file, 'r', encoding='utf-8') as f:
        lines = [l.strip() for l in f if l.strip() and not l.startswith('#')]

    # Parse strings (remove surrounding quotes)
    strings = []
    for line in lines:
        s = line.strip()
        if (s.startswith('"') and s.endswith('"')) or \
           (s.startswith("'") and s.endswith("'")):
            s = s[1:-1]
        strings.append(s)

    if not strings:
        print("ERROR: No strings found in input file")
        sys.exit(1)

    # Generate a unique seed per string (derived from hash of the string)
    encrypted_arrays = []
    seeds = []
    for i, s in enumerate(strings):
        seed = (0x9E3779B97F4A7C15 + i * 0x517CC1B727220A95) & 0xFFFFFFFFFFFFFFFF
        encrypted = encrypt_string(s, seed)
        encrypted_arrays.append(encrypted)
        seeds.append(seed)

    # Write output
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by encrypt_strings.py — DO NOT EDIT\n')
        f.write('// Encrypted strings for DecryptSpace runtime decryption\n')
        f.write(f'// Generated from: {strings_file}\n')
        f.write(f'// Total strings: {len(strings)}\n\n')
        f.write('#ifndef ENCRYPTED_STRINGS_H\n')
        f.write('#define ENCRYPTED_STRINGS_H\n\n')
        f.write('#include <stdint.h>\n#include <stddef.h>\n\n')

        # Enumerate constants
        f.write('// String index constants\n')
        f.write('typedef enum {\n')
        for i, s in enumerate(strings):
            # Create a C-friendly name
            name = ''.join(c if c.isalnum() else '_' for c in s)[:40]
            f.write(f'    ES_{name} = {i},\n')
        f.write('    ES_COUNT\n')
        f.write('} EncryptedStringID;\n\n')

        # Seed table
        f.write('// Decryption seeds (one per string)\n')
        f.write(f'static const uint64_t g_decrypt_seeds[{len(strings)}] = {{\n')
        for seed in seeds:
            f.write(f'    0x{seed:016X}ULL,\n')
        f.write('};\n\n')

        # Encrypted data arrays
        f.write('// Encrypted byte arrays\n')
        for i, (s, enc) in enumerate(zip(strings, encrypted_arrays)):
            name = ''.join(c if c.isalnum() else '_' for c in s)[:30]
            arr = ', '.join(f'0x{b:02X}' for b in enc)
            f.write(f'static const uint8_t enc_{i}_{name}[{len(enc)}] = {{{arr}}};\n')

        f.write('\n// Encrypted string table\n')
        f.write('typedef struct {\n')
        f.write('    const uint8_t *data;\n')
        f.write('    size_t length;\n')
        f.write('    uint64_t seed;\n')
        f.write('} EncryptedStringEntry;\n\n')

        f.write(f'static const EncryptedStringEntry g_encrypted_strings[{len(strings)}] = {{\n')
        for i, (s, enc) in enumerate(zip(strings, encrypted_arrays)):
            name = ''.join(c if c.isalnum() else '_' for c in s)[:30]
            f.write(f'    {{enc_{i}_{name}, {len(enc)}, 0x{seeds[i]:016X}ULL}},\n')
        f.write('};\n\n')

        # DecryptSpace function
        f.write('// splitmix64 PRNG state\n')
        f.write('static inline uint64_t decrypt_splitmix64_next(uint64_t *state) {\n')
        f.write('    uint64_t z = *state;\n')
        f.write('    z = 0xBF58476D1CE4E5B9ULL * (z ^ (z >> 30));\n')
        f.write('    z = 0x94D049BB133111EBULL * (z ^ (z >> 27));\n')
        f.write('    *state -= 0x61C8864680B583EBULL;\n')
        f.write('    return z ^ (z >> 31);\n')
        f.write('}\n\n')

        f.write('// DecryptSpace — runtime string decryption (matches __ obscurity)\n')
        f.write('// Returns a newly allocated C string that the caller must free()\n')
        f.write('static inline char* DecryptSpace(int index) {\n')
        f.write('    if (index < 0 || index >= ES_COUNT) return NULL;\n')
        f.write('    const EncryptedStringEntry *entry = &g_encrypted_strings[index];\n')
        f.write('    char *buf = (char *)malloc(entry->length + 1);\n')
        f.write('    if (!buf) return NULL;\n')
        f.write('    uint64_t state = entry->seed;\n')
        f.write('    for (size_t i = 0; i < entry->length; i++) {\n')
        f.write('        uint64_t r = decrypt_splitmix64_next(&state);\n')
        f.write('        uint8_t key = (uint8_t)((r >> 31) ^ r);\n')
        f.write('        buf[i] = entry->data[i] ^ key;\n')
        f.write('    }\n')
        f.write('    buf[entry->length] = 0;\n')
        f.write('    return buf;\n')
        f.write('}\n\n')

        # NSString convenience
        f.write('#ifdef __OBJC__\n')
        f.write('#import <Foundation/Foundation.h>\n')
        f.write('static inline NSString* DecryptString(int index) {\n')
        f.write('    char *cstr = DecryptSpace(index);\n')
        f.write('    if (!cstr) return nil;\n')
        f.write('    NSString *ns = [NSString stringWithUTF8String:cstr];\n')
        f.write('    memset(cstr, 0, strlen(cstr));\n')
        f.write('    free(cstr);\n')
        f.write('    return ns;\n')
        f.write('}\n')
        f.write('#endif\n\n')

        f.write('#endif // ENCRYPTED_STRINGS_H\n')

    print(f"Generated {output_file}: {len(strings)} encrypted strings, "
          f"{sum(len(e) for e in encrypted_arrays)} total encrypted bytes")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <strings.txt> <output.h>")
        print("  strings.txt: one string per line (quoted or unquoted)")
        print("  output.h:    generated C header with encrypted data + DecryptSpace()")
        sys.exit(1)

    generate_header(sys.argv[1], sys.argv[2])
